comur_api_upload:
    path: /upload
    defaults: {_controller: \Comur\ImageBundle\Controller\UploadController::uploadImageAction }
    options:
        expose: true

comur_api_crop:
    path: /crop
    defaults: {_controller: \Comur\ImageBundle\Controller\UploadController::cropImageAction }
    options:
        expose: true

comur_api_image_library:
    path: /image-library
    defaults: {_controller: \Comur\ImageBundle\Controller\UploadController::getLibraryImagesAction }
    options:
        expose: true
