services:
    Comur\ImageBundle\Form\Type\CroppableImageType:
        tags:
            - { name: form.type, alias: comur_image }

    Comur\ImageBundle\Form\Type\CroppableGalleryType:
        tags:
            - { name: form.type, alias: comur_gallery }
        arguments: ["%comur_image.gallery_dir%", "%comur_image.thumbs_dir%", "%comur_image.gallery_thumb_size%"]

    Comur\ImageBundle\Twig\ThumbExtension:
        tags:
            - { name: twig.extension }
        arguments: ["%comur_image.cropped_image_dir%", "%comur_image.thumbs_dir%", "%comur_image.public_dir%", "%comur_image.translation_domain%", "%comur_image.gallery_dir%"]

    Comur\ImageBundle\Controller\:
        autowire: true
        resource: '../../Controller'
        tags: ['controller.service_arguments']
